services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    ports:
      - '27017:27017'
  api:
    build: .
    ports:
      - "80:80"
    env_file: ".env"
    depends_on:
      - mongo